#!/usr/bin/env node
// Reads .env (or real environment variables, e.g. on Netlify/Vercel) and writes config.js,
// which index.html loads. No packages needed.  Usage:  node build-config.js
const fs = require('fs');
const path = require('path');

function parseEnv(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    out[key] = val;
  }
  return out;
}

const envPath = path.join(__dirname, '.env');
const fromFile = fs.existsSync(envPath) ? parseEnv(fs.readFileSync(envPath, 'utf8')) : {};
const get = k => (process.env[k] !== undefined && process.env[k] !== '' ? process.env[k] : (fromFile[k] || ''));

const required = ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID', 'FIREBASE_APP_ID'];
const missing = required.filter(k => !get(k));
if (missing.length) {
  console.error('Missing from .env (or environment): ' + missing.join(', '));
  console.error('Copy .env.example to .env and fill it in.');
  process.exit(1);
}

const config = {
  firebase: {
    apiKey: get('FIREBASE_API_KEY'),
    authDomain: get('FIREBASE_AUTH_DOMAIN'),
    projectId: get('FIREBASE_PROJECT_ID'),
    storageBucket: get('FIREBASE_STORAGE_BUCKET'),
    messagingSenderId: get('FIREBASE_MESSAGING_SENDER_ID'),
    appId: get('FIREBASE_APP_ID')
  }
};

const body = '// Generated by build-config.js from .env. Do not edit or commit this file.\n' +
  'window.APP_CONFIG = ' + JSON.stringify(config, null, 2) + ';\n';
fs.writeFileSync(path.join(__dirname, 'config.js'), body);
console.log('config.js written.');
